# sample: http://stackoverflow.com/questions/32964953/gitlab-ci-and-msbuild-with-tests
before_script:
  - 'call "%VS120COMNTOOLS%\vsvars32.bat"'
	- 'call dnvminstall.bat'
#  - '".\src\.nuget\NuGet.exe" restore ".\src\CwiDojo.sln"'

build:
  script:
  - echo compilando... 
  - '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" .\src\CwiDojo.sln'
  except:
  - tags