version: 1.0.{build}

branches:
  only:
    - config-ci

install:
  - cinst opencover -version 4.6.166 -source https://nuget.org/api/v2/
#  - cinst coveralls.io -source https://nuget.org/api/v2/
  - install

build_script:
  - cmd: cmd /c dnu restore
  - cmd: cmd /c dnu build src\Accounts.Web

test_script:
#  - cmd: cmd /c dnx test\Accounts.Web.Tests
  - opencover.console -register:user -target:dnx.exe -targetargs:" test\Accounts.Web.Tests test" -targetdir:src\Accounts.Web\bin\Debug\dnx451 -skipautoprops -hideskipped:File -filter:"+[Accounts.Web*]*" -output:coverage.xml

notifications:
  - provider: Slack
    auth_token:
      secure: 5i+buX8e887VjyDyDu440gZcV/O1wRItRSmJgt3vG2V02JypHencdoxeoYeHvM9n
    channel: accounts