version: 1.0.{build}

install:
  - cmd: @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - cmd: cmd /c %userprofile%\.dnx\bin\dnvm install latest
  - cmd: pushd %cd%
  - cmd: cd %userprofile%\.dnx\runtimes\dnx*\bin
  - cmd: set path=%path%;%cd%
  - cmd: popd

build_script:
  - cmd: cmd /c dnu restore
  - cmd: cmd /c dnu build src\Accounts.Web

test_script:
  - cmd: cmd /c dnx test\Accounts.Web.Tests

notifications:
  - provider: Slack
    auth_token:
      secure: 5i+buX8e887VjyDyDu440gZcV/O1wRItRSmJgt3vG2V02JypHencdoxeoYeHvM9n
    channel: accounts