version: 1.0.{build}

install:
  - install

build_script:
  - cmd: cmd /c dnu restore
  - cmd: cmd /c dnu build src\Accounts.Web

test_script:
  - cmd: cmd /c dnx test\Accounts.Web.Tests

notifications:
  - provider: Slack
    auth_token:
      secure: 5i+buX8e887VjyDyDu440gZcV/O1wRItRSmJgt3vG2V02JypHencdoxeoYeHvM9n
    channel: accounts