version: 1.0.{build}

build_script:
  - build

test: off

notifications:
  - provider: Slack
    auth_token:
      secure: 5i+buX8e887VjyDyDu440gZcV/O1wRItRSmJgt3vG2V02JypHencdoxeoYeHvM9n
    channel: accounts