version: 0.1.{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: VpJ55MdBH6PY9Z3gxUyR2lYf83E6iCn38

install:
  - cinst opencover -version 4.6.166 -source https://nuget.org/api/v2/
  - cinst coveralls.io -source https://nuget.org/api/v2/
  - install

build_script:
  - cmd: cmd /c dnvm upgrade
  - cmd: cmd /c dnu restore
  - cmd: cmd /c dnu build src\Accounts.Web

test_script:
  - opencover.console -register:user -target:dnx.exe -targetargs:"--lib c:\projects\accounts\src\Accounts.Web\bin\Debug\dnx451 test\Accounts.Web.Tests test" -skipautoprops -hideskipped:File -filter:"+[Accounts.Web*]*" -output:coverage.xml
  - coveralls.net --opencover coverage.xml

artifacts:
  - path: coverage.xml
